### ISSUE TITLE
Lichess Support via Stylus

### ISSUE THREAD

**Issue by detroyejr** [sharechess/sharechess#2]
I see you submitted a [pull request in the official Lichess repository](https://github.com/lichess-org/lila/pull/10842) to add your anarchy sets so this issue may be unnecessary. But, I thought I'd still offer to base64 encode all the images and submit a similar stylus script that works with Lichess if that's at all helpful.

Formats would be similar to this: https://gist.github.com/detroyejr/8d944c93ff72260160697f0af84a5f26

The project as a whole looks great! Thanks for putting it out there.

**Comment by detroyejr** [comment]
https://twitter.com/lichess/status/1521537647985971200

Congrats on the accepted pull request! 🎉

**Comment by caderek** [comment]
Thank you. I will still keep this issue opened, because I'm making the feature to use any chess set or board on Lichess via Stylus.

**Comment by detroyejr** [comment]
Sounds good. If there's anything I can help with, just let me know.

**Comment by sharechess** [comment]
Ok, the feature is complete an already online!
