### ISSUE TITLE
new piece set just dropped: caliente

### ISSUE THREAD

**Issue by avi-0** [sharechess/sharechess#7]
I made this:

Chess piece set with a cartoon 3D-esque style and a focus on readability, loosely inspired by [california](https://sites.google.com/view/jerrychess/home) by Jerry S.
https://github.com/avi-0/caliente

![image](https://github.com/sharechess/sharechess/assets/25254726/4ea742c8-6f29-4d27-b7fd-dfaccf36c177)

Let me know if you have any feedback though first, I'm planning to submit this to lichess but I'm struggling to restrain myself from rushing into that before I make sure I'm not going to tweak something again later (upd just tweaked the rook smh), should sit on it a few days.

I see sharechess usually has 4 variants for all the piece sets - any ideas for those?

And also lmk if LICENSE.txt looks ok (CC-SA-NC-4.0), never licensed anything before.

**Comment by caderek** [comment]
Looks good, license is ok. About color variants - you could either provide two additional color variants, or I will pick some colors for you. Just let me know if you prefer to do it yourself.

**Comment by avi-0** [comment]
Yeah I'm fine if you pick something for the other two, idk myself really. I have some ideas to make a meme variant (arming the bishops with sniper rifles and stuff like that) but that'd be quite a bit more effort for later. For now I've just figured out the last couple of things that bothered me about the rooks and the shadows, I'm quite satisfied with the current version in the repo. Should be good to put in.

**Comment by avi-0** [comment]
actually forgot to update the wood set with those, that included an issue with the white queen's shadow, will fix  later today

**Comment by caderek** [comment]
I cleaned them up a bit (to reduce size), here are final files:

https://github.com/sharechess/sharechess/tree/main/public/pieces/caliente
https://github.com/sharechess/sharechess/tree/main/public/pieces/caliente_wood
https://github.com/sharechess/sharechess/tree/main/public/pieces/caliente_blue
https://github.com/sharechess/sharechess/tree/main/public/pieces/caliente_pink

Pieces are already deployed to [sharechess.github.io](https://sharechess.github.io/)

**Comment by avi-0** [comment]
tysm!!
